### ISSUE TITLE
Brainstorming how to add videos

### ISSUE THREAD

**Issue by WarpWing** [p0lygun/wallpaper-engine#10]
Couldn't you add videos by using open cv to capture the videos, getting the frames, syncing the frames to a clock, and then converting each frame to a surface object(by way of using an image buffer?)

**Comment by WarpWing** [comment]
(This also means that you could add gifs with a little bit of coding)

**Comment by p0lygun** [comment]
> Couldn't you add videos by using open cv to capture the videos, getting the frames, syncing the frames to a clock, and then converting each frame to a surface object(by way of using an image buffer?)

As kivy supports video playback by default 
It is really not that hard to put a video as a wallpaper 
As for gif I believe that can also be done easily 
I think I can get the video as wallpaper done today itself
