### ISSUE TITLE
Creates a fullscreen window instead of "changing" the wallpaper when I run runner.py

### ISSUE THREAD

**Issue by ManHinnn0509** [p0lygun/wallpaper-engine#5]
I saw the video examples on your YouTube channel however I wasn't able to get the same effect.
![img](https://user-images.githubusercontent.com/79153615/126255444-ef128f93-86b9-4e1f-9505-b43414801264.png)

Both pygame and pywin32 are the same version as the requirement.txt
I ran "python runner.py sin_wave" in cmd.exe

BTW, really cool idea. Thanks for creating this.
I also wanna know is it possible to set the wallpaper as video using pygame or moviepy?

**Comment by p0lygun** [comment]
ohhh this wallpaper was in the repo when i was using pygame as the back-end (to draw the wallpaper) but since i have switched to kivy 
if u want to use the same use the [backup/pygame](https://github.com/p0lygun/wallpaper-engine/tree/backup/pygame) branch

**Comment by p0lygun** [comment]
but beware that branch is quiet a mess so  
to run use the command `python runner.py -W=sin_wave`

**Comment by p0lygun** [comment]
as for the video as kivy supports video output we can totally set a video as a wallpaper
pretty much anything that does not require input and can be done in kivy can be put as a wallpaper
